# Default configuration
SUPERMAVEN_ENABLED=${SUPERMAVEN_ENABLED:-true}
SUPERMAVEN_LOG_LEVEL=${SUPERMAVEN_LOG_LEVEL:-"info"}
SUPERMAVEN_COMPLETION_TRIGGER=${SUPERMAVEN_COMPLETION_TRIGGER:-"^X^M"}
SUPERMAVEN_AUTO_START=${SUPERMAVEN_AUTO_START:-true}
SUPERMAVEN_COMPLETION_COLOR=${SUPERMAVEN_COMPLETION_COLOR:-"8"}  # Default to gray
SUPERMAVEN_ACCEPT_SUGGESTION_KEY=${SUPERMAVEN_ACCEPT_SUGGESTION_KEY:-"^E"} # Default to Ctrl-E
